settings:
  gui:
    title: "&8ʀᴀɴᴅᴏᴍ ᴛᴇʟᴇᴘᴏʀᴛ"
    rows: 3
  cooldown-seconds: 60
  max-retries: 50
  sounds:
    gui-click: "UI_BUTTON_CLICK"
    countdown-tick: "BLOCK_NOTE_BLOCK_CHIME"
    teleport-success: "ENTITY_PLAYER_LEVELUP"
    cooldown-error: "ENTITY_VILLAGER_NO"
  worlds:
    world:
      slot: 11
      min-y: 63
      max-y: 120
      max-radius: 5000
      min-radius: 100
      item: GRASS_BLOCK
      name: "&#facc15ᴏᴠᴇʀᴡᴏʀʟᴅ"
      lore:
        - "&fClick to randomly teleport"
    world_nether:
      slot: 13
      min-y: 32
      max-y: 110
      max-radius: 2000
      min-radius: 50
      item: NETHERRACK
      name: "&#facc15ɴᴇᴛʜᴇʀ"
      lore:
        - "&fClick to randomly teleport"
    world_the_end:
      slot: 15
      min-y: 55
      max-y: 75
      max-radius: 3000
      min-radius: 100
      item: END_STONE
      name: "&#facc15ᴇɴᴅ"
      lore:
        - "&fClick to randomly teleport"
